name: clean_riverpod
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.1
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.9
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  swipeable_page_route: ^0.4.1
  easy_localization: ^3.0.3
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod: ^2.4.9
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/svg/
    - assets/audio/
    - assets/lotties/
    - assets/translations/

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/image/img_app_icon_border.png
  android_12:
    image: assets/image/img_app_icon_border.png
  android: true
  ios: true

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/image/img_app_icon.png
  min_sdk_android: 21

#  dart run flutter_native_splash:create
#  flutter pub run flutter_launcher_icons
#  flutter pub run easy_localization:generate -S assets/translations -f keys -o locale_keys.g.dart